// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/embeddings.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for embeddings
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_proto_embeddings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embeddings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_embeddings_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Response message for embeddings
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_proto_embeddings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embeddings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_embeddings_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_proto_embeddings_proto protoreflect.FileDescriptor

const file_proto_embeddings_proto_rawDesc = "" +
	"\n" +
	"\x16proto/embeddings.proto\x12\tinference\"&\n" +
	"\x10EmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding2W\n" +
	"\n" +
	"Inferencer\x12I\n" +
	"\fGetEmbedding\x12\x1b.inference.EmbeddingRequest\x1a\x1c.inference.EmbeddingResponseB-Z+github.com/garv/go-rag/services/proto;protob\x06proto3"

var (
	file_proto_embeddings_proto_rawDescOnce sync.Once
	file_proto_embeddings_proto_rawDescData []byte
)

func file_proto_embeddings_proto_rawDescGZIP() []byte {
	file_proto_embeddings_proto_rawDescOnce.Do(func() {
		file_proto_embeddings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_embeddings_proto_rawDesc), len(file_proto_embeddings_proto_rawDesc)))
	})
	return file_proto_embeddings_proto_rawDescData
}

var file_proto_embeddings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_embeddings_proto_goTypes = []any{
	(*EmbeddingRequest)(nil),  // 0: inference.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 1: inference.EmbeddingResponse
}
var file_proto_embeddings_proto_depIdxs = []int32{
	0, // 0: inference.Inferencer.GetEmbedding:input_type -> inference.EmbeddingRequest
	1, // 1: inference.Inferencer.GetEmbedding:output_type -> inference.EmbeddingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_embeddings_proto_init() }
func file_proto_embeddings_proto_init() {
	if File_proto_embeddings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_embeddings_proto_rawDesc), len(file_proto_embeddings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embeddings_proto_goTypes,
		DependencyIndexes: file_proto_embeddings_proto_depIdxs,
		MessageInfos:      file_proto_embeddings_proto_msgTypes,
	}.Build()
	File_proto_embeddings_proto = out.File
	file_proto_embeddings_proto_goTypes = nil
	file_proto_embeddings_proto_depIdxs = nil
}
