// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-rag/ent/ent/chunk"
	"go-rag/ent/ent/embedding"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmbeddingCreate is the builder for creating a Embedding entity.
type EmbeddingCreate struct {
	config
	mutation *EmbeddingMutation
	hooks    []Hook
}

// SetVector sets the "vector" field.
func (_c *EmbeddingCreate) SetVector(v []float32) *EmbeddingCreate {
	_c.mutation.SetVector(v)
	return _c
}

// SetChunkID sets the "chunk" edge to the Chunk entity by ID.
func (_c *EmbeddingCreate) SetChunkID(id int) *EmbeddingCreate {
	_c.mutation.SetChunkID(id)
	return _c
}

// SetNillableChunkID sets the "chunk" edge to the Chunk entity by ID if the given value is not nil.
func (_c *EmbeddingCreate) SetNillableChunkID(id *int) *EmbeddingCreate {
	if id != nil {
		_c = _c.SetChunkID(*id)
	}
	return _c
}

// SetChunk sets the "chunk" edge to the Chunk entity.
func (_c *EmbeddingCreate) SetChunk(v *Chunk) *EmbeddingCreate {
	return _c.SetChunkID(v.ID)
}

// Mutation returns the EmbeddingMutation object of the builder.
func (_c *EmbeddingCreate) Mutation() *EmbeddingMutation {
	return _c.mutation
}

// Save creates the Embedding in the database.
func (_c *EmbeddingCreate) Save(ctx context.Context) (*Embedding, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmbeddingCreate) SaveX(ctx context.Context) *Embedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmbeddingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmbeddingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmbeddingCreate) check() error {
	if _, ok := _c.mutation.Vector(); !ok {
		return &ValidationError{Name: "vector", err: errors.New(`ent: missing required field "Embedding.vector"`)}
	}
	return nil
}

func (_c *EmbeddingCreate) sqlSave(ctx context.Context) (*Embedding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmbeddingCreate) createSpec() (*Embedding, *sqlgraph.CreateSpec) {
	var (
		_node = &Embedding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(embedding.Table, sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Vector(); ok {
		_spec.SetField(embedding.FieldVector, field.TypeJSON, value)
		_node.Vector = value
	}
	if nodes := _c.mutation.ChunkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   embedding.ChunkTable,
			Columns: []string{embedding.ChunkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chunk_embeddings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmbeddingCreateBulk is the builder for creating many Embedding entities in bulk.
type EmbeddingCreateBulk struct {
	config
	err      error
	builders []*EmbeddingCreate
}

// Save creates the Embedding entities in the database.
func (_c *EmbeddingCreateBulk) Save(ctx context.Context) ([]*Embedding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Embedding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmbeddingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmbeddingCreateBulk) SaveX(ctx context.Context) []*Embedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmbeddingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmbeddingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
