// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-rag/ent/ent/securityquestion"
	"go-rag/ent/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// SecurityQuestion is the model entity for the SecurityQuestion schema.
type SecurityQuestion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer string `json:"answer,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecurityQuestionQuery when eager-loading is set.
	Edges                   SecurityQuestionEdges `json:"edges"`
	user_security_questions *uuid.UUID
	selectValues            sql.SelectValues
}

// SecurityQuestionEdges holds the relations/edges for other nodes in the graph.
type SecurityQuestionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecurityQuestionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecurityQuestion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case securityquestion.FieldQuestion, securityquestion.FieldAnswer:
			values[i] = new(sql.NullString)
		case securityquestion.FieldCreatedAt, securityquestion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case securityquestion.FieldID:
			values[i] = new(uuid.UUID)
		case securityquestion.ForeignKeys[0]: // user_security_questions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecurityQuestion fields.
func (_m *SecurityQuestion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case securityquestion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case securityquestion.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case securityquestion.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = value.String
			}
		case securityquestion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case securityquestion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case securityquestion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_security_questions", values[i])
			} else if value.Valid {
				_m.user_security_questions = new(uuid.UUID)
				*_m.user_security_questions = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecurityQuestion.
// This includes values selected through modifiers, order, etc.
func (_m *SecurityQuestion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SecurityQuestion entity.
func (_m *SecurityQuestion) QueryUser() *UserQuery {
	return NewSecurityQuestionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this SecurityQuestion.
// Note that you need to call SecurityQuestion.Unwrap() before calling this method if this SecurityQuestion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SecurityQuestion) Update() *SecurityQuestionUpdateOne {
	return NewSecurityQuestionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SecurityQuestion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SecurityQuestion) Unwrap() *SecurityQuestion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecurityQuestion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SecurityQuestion) String() string {
	var builder strings.Builder
	builder.WriteString("SecurityQuestion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(_m.Answer)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SecurityQuestions is a parsable slice of SecurityQuestion.
type SecurityQuestions []*SecurityQuestion
