// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-rag/ent/ent/predicate"
	"go-rag/ent/ent/securityquestion"
	"go-rag/ent/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SecurityQuestionUpdate is the builder for updating SecurityQuestion entities.
type SecurityQuestionUpdate struct {
	config
	hooks    []Hook
	mutation *SecurityQuestionMutation
}

// Where appends a list predicates to the SecurityQuestionUpdate builder.
func (_u *SecurityQuestionUpdate) Where(ps ...predicate.SecurityQuestion) *SecurityQuestionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestion sets the "question" field.
func (_u *SecurityQuestionUpdate) SetQuestion(v string) *SecurityQuestionUpdate {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *SecurityQuestionUpdate) SetNillableQuestion(v *string) *SecurityQuestionUpdate {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *SecurityQuestionUpdate) SetAnswer(v string) *SecurityQuestionUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *SecurityQuestionUpdate) SetNillableAnswer(v *string) *SecurityQuestionUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SecurityQuestionUpdate) SetUpdatedAt(v time.Time) *SecurityQuestionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SecurityQuestionUpdate) SetUserID(id uuid.UUID) *SecurityQuestionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SecurityQuestionUpdate) SetUser(v *User) *SecurityQuestionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SecurityQuestionMutation object of the builder.
func (_u *SecurityQuestionUpdate) Mutation() *SecurityQuestionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SecurityQuestionUpdate) ClearUser() *SecurityQuestionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecurityQuestionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityQuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecurityQuestionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityQuestionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SecurityQuestionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := securityquestion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityQuestionUpdate) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := securityquestion.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := securityquestion.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.answer": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecurityQuestion.user"`)
	}
	return nil
}

func (_u *SecurityQuestionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securityquestion.Table, securityquestion.Columns, sqlgraph.NewFieldSpec(securityquestion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(securityquestion.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(securityquestion.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(securityquestion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   securityquestion.UserTable,
			Columns: []string{securityquestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   securityquestion.UserTable,
			Columns: []string{securityquestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityquestion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecurityQuestionUpdateOne is the builder for updating a single SecurityQuestion entity.
type SecurityQuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecurityQuestionMutation
}

// SetQuestion sets the "question" field.
func (_u *SecurityQuestionUpdateOne) SetQuestion(v string) *SecurityQuestionUpdateOne {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *SecurityQuestionUpdateOne) SetNillableQuestion(v *string) *SecurityQuestionUpdateOne {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *SecurityQuestionUpdateOne) SetAnswer(v string) *SecurityQuestionUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *SecurityQuestionUpdateOne) SetNillableAnswer(v *string) *SecurityQuestionUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SecurityQuestionUpdateOne) SetUpdatedAt(v time.Time) *SecurityQuestionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SecurityQuestionUpdateOne) SetUserID(id uuid.UUID) *SecurityQuestionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SecurityQuestionUpdateOne) SetUser(v *User) *SecurityQuestionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SecurityQuestionMutation object of the builder.
func (_u *SecurityQuestionUpdateOne) Mutation() *SecurityQuestionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SecurityQuestionUpdateOne) ClearUser() *SecurityQuestionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SecurityQuestionUpdate builder.
func (_u *SecurityQuestionUpdateOne) Where(ps ...predicate.SecurityQuestion) *SecurityQuestionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecurityQuestionUpdateOne) Select(field string, fields ...string) *SecurityQuestionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SecurityQuestion entity.
func (_u *SecurityQuestionUpdateOne) Save(ctx context.Context) (*SecurityQuestion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityQuestionUpdateOne) SaveX(ctx context.Context) *SecurityQuestion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecurityQuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityQuestionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SecurityQuestionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := securityquestion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityQuestionUpdateOne) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := securityquestion.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := securityquestion.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.answer": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecurityQuestion.user"`)
	}
	return nil
}

func (_u *SecurityQuestionUpdateOne) sqlSave(ctx context.Context) (_node *SecurityQuestion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securityquestion.Table, securityquestion.Columns, sqlgraph.NewFieldSpec(securityquestion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecurityQuestion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securityquestion.FieldID)
		for _, f := range fields {
			if !securityquestion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != securityquestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(securityquestion.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(securityquestion.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(securityquestion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   securityquestion.UserTable,
			Columns: []string{securityquestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   securityquestion.UserTable,
			Columns: []string{securityquestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SecurityQuestion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityquestion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
