// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-rag/ent/ent/securityquestion"
	"go-rag/ent/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SecurityQuestionCreate is the builder for creating a SecurityQuestion entity.
type SecurityQuestionCreate struct {
	config
	mutation *SecurityQuestionMutation
	hooks    []Hook
}

// SetQuestion sets the "question" field.
func (_c *SecurityQuestionCreate) SetQuestion(v string) *SecurityQuestionCreate {
	_c.mutation.SetQuestion(v)
	return _c
}

// SetAnswer sets the "answer" field.
func (_c *SecurityQuestionCreate) SetAnswer(v string) *SecurityQuestionCreate {
	_c.mutation.SetAnswer(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SecurityQuestionCreate) SetCreatedAt(v time.Time) *SecurityQuestionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SecurityQuestionCreate) SetNillableCreatedAt(v *time.Time) *SecurityQuestionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SecurityQuestionCreate) SetUpdatedAt(v time.Time) *SecurityQuestionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SecurityQuestionCreate) SetNillableUpdatedAt(v *time.Time) *SecurityQuestionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SecurityQuestionCreate) SetID(v uuid.UUID) *SecurityQuestionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SecurityQuestionCreate) SetNillableID(v *uuid.UUID) *SecurityQuestionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *SecurityQuestionCreate) SetUserID(id uuid.UUID) *SecurityQuestionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SecurityQuestionCreate) SetUser(v *User) *SecurityQuestionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SecurityQuestionMutation object of the builder.
func (_c *SecurityQuestionCreate) Mutation() *SecurityQuestionMutation {
	return _c.mutation
}

// Save creates the SecurityQuestion in the database.
func (_c *SecurityQuestionCreate) Save(ctx context.Context) (*SecurityQuestion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecurityQuestionCreate) SaveX(ctx context.Context) *SecurityQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityQuestionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityQuestionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecurityQuestionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := securityquestion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := securityquestion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := securityquestion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecurityQuestionCreate) check() error {
	if _, ok := _c.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "SecurityQuestion.question"`)}
	}
	if v, ok := _c.mutation.Question(); ok {
		if err := securityquestion.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.question": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "SecurityQuestion.answer"`)}
	}
	if v, ok := _c.mutation.Answer(); ok {
		if err := securityquestion.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "SecurityQuestion.answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SecurityQuestion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SecurityQuestion.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SecurityQuestion.user"`)}
	}
	return nil
}

func (_c *SecurityQuestionCreate) sqlSave(ctx context.Context) (*SecurityQuestion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecurityQuestionCreate) createSpec() (*SecurityQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &SecurityQuestion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(securityquestion.Table, sqlgraph.NewFieldSpec(securityquestion.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Question(); ok {
		_spec.SetField(securityquestion.FieldQuestion, field.TypeString, value)
		_node.Question = value
	}
	if value, ok := _c.mutation.Answer(); ok {
		_spec.SetField(securityquestion.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(securityquestion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(securityquestion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   securityquestion.UserTable,
			Columns: []string{securityquestion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_security_questions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SecurityQuestionCreateBulk is the builder for creating many SecurityQuestion entities in bulk.
type SecurityQuestionCreateBulk struct {
	config
	err      error
	builders []*SecurityQuestionCreate
}

// Save creates the SecurityQuestion entities in the database.
func (_c *SecurityQuestionCreateBulk) Save(ctx context.Context) ([]*SecurityQuestion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecurityQuestion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecurityQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecurityQuestionCreateBulk) SaveX(ctx context.Context) []*SecurityQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
