// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-rag/ent/ent/project"
	"go-rag/ent/ent/queryresult"
	"go-rag/ent/ent/user"
	"go-rag/ent/ent/userprompt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserPromptCreate is the builder for creating a UserPrompt entity.
type UserPromptCreate struct {
	config
	mutation *UserPromptMutation
	hooks    []Hook
}

// SetQueryText sets the "query_text" field.
func (_c *UserPromptCreate) SetQueryText(v string) *UserPromptCreate {
	_c.mutation.SetQueryText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPromptCreate) SetCreatedAt(v time.Time) *UserPromptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPromptCreate) SetNillableCreatedAt(v *time.Time) *UserPromptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserPromptCreate) SetUserID(id uuid.UUID) *UserPromptCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *UserPromptCreate) SetNillableUserID(id *uuid.UUID) *UserPromptCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPromptCreate) SetUser(v *User) *UserPromptCreate {
	return _c.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *UserPromptCreate) SetProjectID(id int) *UserPromptCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_c *UserPromptCreate) SetNillableProjectID(id *int) *UserPromptCreate {
	if id != nil {
		_c = _c.SetProjectID(*id)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *UserPromptCreate) SetProject(v *Project) *UserPromptCreate {
	return _c.SetProjectID(v.ID)
}

// AddResultIDs adds the "results" edge to the QueryResult entity by IDs.
func (_c *UserPromptCreate) AddResultIDs(ids ...int) *UserPromptCreate {
	_c.mutation.AddResultIDs(ids...)
	return _c
}

// AddResults adds the "results" edges to the QueryResult entity.
func (_c *UserPromptCreate) AddResults(v ...*QueryResult) *UserPromptCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResultIDs(ids...)
}

// Mutation returns the UserPromptMutation object of the builder.
func (_c *UserPromptCreate) Mutation() *UserPromptMutation {
	return _c.mutation
}

// Save creates the UserPrompt in the database.
func (_c *UserPromptCreate) Save(ctx context.Context) (*UserPrompt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPromptCreate) SaveX(ctx context.Context) *UserPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPromptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPromptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPromptCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userprompt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPromptCreate) check() error {
	if _, ok := _c.mutation.QueryText(); !ok {
		return &ValidationError{Name: "query_text", err: errors.New(`ent: missing required field "UserPrompt.query_text"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPrompt.created_at"`)}
	}
	return nil
}

func (_c *UserPromptCreate) sqlSave(ctx context.Context) (*UserPrompt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPromptCreate) createSpec() (*UserPrompt, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPrompt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userprompt.Table, sqlgraph.NewFieldSpec(userprompt.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.QueryText(); ok {
		_spec.SetField(userprompt.FieldQueryText, field.TypeString, value)
		_node.QueryText = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userprompt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userprompt.UserTable,
			Columns: []string{userprompt.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_queries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userprompt.ProjectTable,
			Columns: []string{userprompt.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_queries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprompt.ResultsTable,
			Columns: []string{userprompt.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(queryresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPromptCreateBulk is the builder for creating many UserPrompt entities in bulk.
type UserPromptCreateBulk struct {
	config
	err      error
	builders []*UserPromptCreate
}

// Save creates the UserPrompt entities in the database.
func (_c *UserPromptCreateBulk) Save(ctx context.Context) ([]*UserPrompt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPrompt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPromptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPromptCreateBulk) SaveX(ctx context.Context) []*UserPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPromptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPromptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
