// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-rag/ent/ent/predicate"
	"go-rag/ent/ent/userprompt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPromptDelete is the builder for deleting a UserPrompt entity.
type UserPromptDelete struct {
	config
	hooks    []Hook
	mutation *UserPromptMutation
}

// Where appends a list predicates to the UserPromptDelete builder.
func (_d *UserPromptDelete) Where(ps ...predicate.UserPrompt) *UserPromptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserPromptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPromptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserPromptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userprompt.Table, sqlgraph.NewFieldSpec(userprompt.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserPromptDeleteOne is the builder for deleting a single UserPrompt entity.
type UserPromptDeleteOne struct {
	_d *UserPromptDelete
}

// Where appends a list predicates to the UserPromptDelete builder.
func (_d *UserPromptDeleteOne) Where(ps ...predicate.UserPrompt) *UserPromptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserPromptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userprompt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPromptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
