// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Embedding is the predicate function for embedding builders.
type Embedding func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// QueryResult is the predicate function for queryresult builders.
type QueryResult func(*sql.Selector)

// SecurityQuestion is the predicate function for securityquestion builders.
type SecurityQuestion func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPrompt is the predicate function for userprompt builders.
type UserPrompt func(*sql.Selector)
