-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create "projects" table
CREATE TABLE "public"."projects" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "user_projects" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "projects_users_projects" FOREIGN KEY ("user_projects") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "documents" table
CREATE TABLE "public"."documents" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "storage_path" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'uploaded',
  "created_at" timestamptz NOT NULL,
  "project_documents" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "documents_projects_documents" FOREIGN KEY ("project_documents") REFERENCES "public"."projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "chunks" table
CREATE TABLE "public"."chunks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "index" bigint NOT NULL,
  "content" text NOT NULL,
  "document_chunks" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "chunks_documents_chunks" FOREIGN KEY ("document_chunks") REFERENCES "public"."documents" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "embeddings" table
CREATE TABLE "public"."embeddings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "vector" jsonb NOT NULL,
  "chunk_embeddings" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "embeddings_chunks_embeddings" FOREIGN KEY ("chunk_embeddings") REFERENCES "public"."chunks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "user_prompts" table
CREATE TABLE "public"."user_prompts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "query_text" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "project_queries" bigint NULL,
  "user_queries" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_prompts_projects_queries" FOREIGN KEY ("project_queries") REFERENCES "public"."projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "user_prompts_users_queries" FOREIGN KEY ("user_queries") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "query_results" table
CREATE TABLE "public"."query_results" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rank" bigint NOT NULL,
  "score" double precision NOT NULL,
  "content_snippet" text NOT NULL,
  "document_query_results" bigint NULL,
  "user_prompt_results" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "query_results_documents_query_results" FOREIGN KEY ("document_query_results") REFERENCES "public"."documents" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "query_results_user_prompts_results" FOREIGN KEY ("user_prompt_results") REFERENCES "public"."user_prompts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
