-- Create "users" table
CREATE TABLE "users" (
  "id" uuid NOT NULL,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "email_confirmed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "projects" table
CREATE TABLE "projects" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "user_projects" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "projects_users_projects" FOREIGN KEY ("user_projects") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "documents" table
CREATE TABLE "documents" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "storage_path" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'uploaded',
  "created_at" timestamptz NOT NULL,
  "project_documents" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "documents_projects_documents" FOREIGN KEY ("project_documents") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "chunks" table
CREATE TABLE "chunks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "index" bigint NOT NULL,
  "content" text NOT NULL,
  "document_chunks" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "chunks_documents_chunks" FOREIGN KEY ("document_chunks") REFERENCES "documents" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "embeddings" table
CREATE TABLE "embeddings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "vector" jsonb NOT NULL,
  "chunk_embeddings" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "embeddings_chunks_embeddings" FOREIGN KEY ("chunk_embeddings") REFERENCES "chunks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "user_prompts" table
CREATE TABLE "user_prompts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "query_text" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "project_queries" bigint NULL,
  "user_queries" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_prompts_projects_queries" FOREIGN KEY ("project_queries") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "user_prompts_users_queries" FOREIGN KEY ("user_queries") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "query_results" table
CREATE TABLE "query_results" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rank" bigint NOT NULL,
  "score" double precision NOT NULL,
  "content_snippet" text NOT NULL,
  "document_query_results" bigint NULL,
  "user_prompt_results" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "query_results_documents_query_results" FOREIGN KEY ("document_query_results") REFERENCES "documents" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "query_results_user_prompts_results" FOREIGN KEY ("user_prompt_results") REFERENCES "user_prompts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "sessions" table
CREATE TABLE "sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "session_id" uuid NOT NULL,
  "session_type" character varying NOT NULL,
  "access_token" character varying NOT NULL,
  "refresh_token" character varying NULL,
  "device_name" character varying NULL,
  "last_sync_time" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "ip_address" character varying NULL,
  "user_agent" character varying NULL,
  "metadata" jsonb NULL,
  "sessions_userids" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("sessions_userids") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "sessions_access_token_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_access_token_key" ON "sessions" ("access_token");
-- Create index "sessions_session_id_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_session_id_key" ON "sessions" ("session_id");
